apiVersion: v1
kind: Service
metadata:
  labels:
    service: postgresql
  name: postgresql
spec:
  ports:
  - name: "5432"
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    service: postgresql
