apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgresql
  labels:
    service: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      service: postgresql
  template:
    metadata:
      labels:
        service: postgresql
    spec:
      containers:
      - env:
        - name: POSTGRES_USER
          value: staffservice
        - name: POSTGRES_PASSWORD
        image: docker.io/postgres:9.5.1
        name: postgresql
        ports:
        - containerPort: 5432
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 20
          timeoutSeconds: 10
          failureThreshold: 3
        livenessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 120
          timeoutSeconds: 10
          failureThreshold: 3
      restartPolicy: Always
