version: '2'
services:
    shiftwork-app:
        image: staffservice
        external_links:
            - staffservice-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=dev
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/staffservice
        ports:
            - 8080:8080
    postgresql:
        extends:
            file: postgresql.yml
            service: staffservice-postgresql
